### ISSUE TITLE
Exposed MongoDB Access URI

### ISSUE THREAD

**Issue by 0xBenCantCode** [EMcNugget/ADS-B-Military-Analytics#21]
mongodb+srv://xxxxx:xxxxx@mildata.oyy7jmp.mongodb.net/
```
milData
    └── historicalData (32 docs, 7.8 MB)
  admin
  local
    └── oplog.rs (0 docs, Unknown)
```

**Comment by EMcNugget** [comment]
> mongodb+srv://xxxxx:xxxxx@mildata.oyy7jmp.mongodb.net/
> 
> ```
> 
> milData
> 
>     └── historicalData (32 docs, 7.8 MB)
> 
>   admin
> 
>   local
> 
>     └── oplog.rs (0 docs, Unknown)
> 
> ```

Looking into it.
